"""Initial migration reflecting existing schema

Revision ID: 047f8466cffb
Revises: eea3b7e332ab
Create Date: 2024-06-15 23:41:40.015878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '047f8466cffb'
down_revision = 'eea3b7e332ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('input_format', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('output_format', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sample_path', sa.String(length=200), nullable=False))
        batch_op.drop_column('inputFormat')
        batch_op.drop_column('outputFormat')
        batch_op.drop_column('Id')
        batch_op.drop_column('samplePath')

    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('problem_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('code_text', sa.String(length=500), nullable=False))
        batch_op.drop_constraint('FK__submit__problemI__06CD04F7', type_='foreignkey')
        batch_op.create_foreign_key(None, 'problem', ['problem_id'], ['id'])
        batch_op.drop_column('Id')
        batch_op.drop_column('problemId')
        batch_op.drop_column('codeText')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codeText', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('problemId', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__submit__problemI__06CD04F7', 'problem', ['problemId'], ['Id'])
        batch_op.drop_column('code_text')
        batch_op.drop_column('problem_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('samplePath', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('outputFormat', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inputFormat', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_column('sample_path')
        batch_op.drop_column('output_format')
        batch_op.drop_column('input_format')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
