"""Recreate tables

Revision ID: 288bec4f17fe
Revises: 
Create Date: 2024-06-17 09:12:11.249483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288bec4f17fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('input_format', sa.String(length=100), nullable=True),
    sa.Column('output_format', sa.String(length=100), nullable=True),
    sa.Column('sample_path', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code_text', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=200), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submit')
    op.drop_table('problem')
    # ### end Alembic commands ###
