"""Initial migration

Revision ID: abf4f479fd25
Revises: 
Create Date: 2024-06-19 15:25:04.852756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf4f479fd25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.alter_column('sample_path',
               existing_type=sa.NVARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('problem_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint('FK__submissio__probl__7849DB76', type_='foreignkey')
        batch_op.create_foreign_key(None, 'problem', ['problem_id'], ['id'])
        batch_op.drop_column('Id')
        batch_op.drop_column('problemId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problemId', sa.NVARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Id', sa.NVARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text('(newid())'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__submissio__probl__7849DB76', 'problem', ['problemId'], ['id'])
        batch_op.drop_column('problem_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.alter_column('sample_path',
               existing_type=sa.String(length=200),
               type_=sa.NVARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
