"""Initial migration.

Revision ID: eea3b7e332ab
Revises: 
Create Date: 2024-06-15 18:30:34.299562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'eea3b7e332ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ToDo')
    op.drop_table('submission')
    op.drop_table('problem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('inputFormat', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('outputFormat', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK__problem__3214EC07C5596347')
    )
    op.create_table('submission',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('problemId', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('codeText', sa.NVARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('runtime', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('memory', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['problemId'], ['problem.Id'], name='FK__submissio__probl__71D1E811'),
    sa.PrimaryKeyConstraint('Id', name='PK__submissi__3214EC07D1E2AEDF')
    )
    op.create_table('ToDo',
    sa.Column('Id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('url', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('completed', mssql.BIT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK__ToDo__3214EC07B2222224')
    )
    # ### end Alembic commands ###
